### PR TITLE
Refactor item.get function to return an array of ValueField objects

### PR DESCRIPTION
**Pull request by Mearman**
When fields param is passed, it appears the response is a ValueField[]

### CODE REVIEW

**Comment by jodyheavener** [comment]
Hey @Mearman, thanks for this patch! Looks great, and I've also added an additional case and tests.

**Comment by Mearman** [comment]
> Hey @Mearman, thanks for this patch! Looks great, and I've also added an additional case and tests.

Haha I had forgotten about this

**Comment by Mearman** [comment]
@Mearman now this is merged, could you push a release please?

**Comment by Mearman** [comment]
@jodyheavener now this is merged, could you push a release please?

**Pull request merged**
